config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :users, only: [:show]
  resources :places do
    collection do
      get 'search'
    end
  end
  resources :reviews do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :reviews, :dependent => :destroy
  
  accepts_nested_attributes_for :reviews
  def review_average
    self.reviews.average(:recommend_rate).round
  end
  def wifi_average
    self.reviews.average(:wifi_rate).round
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  belongs_to :user, dependent: :destroy
  has_one_attached :image
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_one_attached :image
  # SNSアカウントでログインできる機能
  devise :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :image])
  end
end

app/controllers/places_controller.rb
require 'net/http'
require 'uri'
require 'rexml/document'

class PlacesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

  def search
    keyword = params[:keyword]
    @appid = ENV["YAHOO_APP_ID"]
    url = URI.parse(URI.escape("https://map.yahooapis.jp/search/local/V1/localSearch?appid=#{@appid}&query=#{keyword}&results=20&detail=full"))
    res = Net::HTTP.start(url.host, url.port, use_ssl: true){|http|
    http.get(url.path + "?" + url.query);}

    doc = REXML::Document.new(res.body)

    @names = doc.elements.each('YDF/Feature/Name'){|i|} 
    @geometries = doc.elements.each('YDF/Feature/Geometry/Coordinates'){|i|}
    @stations = doc.elements.each('YDF/Feature/Property/Station/Name'){|i|}
    @urls = doc.elements.each('YDF/Feature/Property/Detail/PcUrl1'){|i|}
    @addresses = doc.elements.each('YDF/Feature/Property/Address'){|i|}
    num = 0
    @places = []
    while num < 20 do
      unless @names[num].blank? 
        name = @names[num].text
        geometry = @geometries[num].text
        @lat = geometry.split(",")[0].to_f
        @lon = geometry.split(",")[1].to_f
        @station = @stations[num].text
        @url = @urls[num].text
        @address = @addresses[num].text
        a_place = {name: name, lat: @lat, lon: @lon, area: @station, url: @url, address: @address}
        @places << a_place
        num += 1
      else
        break
      end
    end
  end
  
  def index
    @appid = ENV["YAHOO_APP_ID"]
    @reviews = Review.all
    areas = []
    @locations = []
    
    @reviews.each do |review|
    area = review.place[:area_name]
    areas << area
    
    lon = review.place[:lon]
    lat = review.place[:lat]
    id = review.place[:id]
    place_name = review.place[:place_name]
    @locations << {lon: lon, lat: lat, id: id, placeName: place_name}
    end
    @areas = areas.uniq
    gon.locations = @locations
  end
  
  def show
    @place = Place.find(params[:id])
    @reviews = Review.where(place_id: params[:id])
    @appid = ENV["YAHOO_APP_ID"]
  end
  
  def new
    @place = Place.new
    @place.reviews.build
    @name = params[:name]
    @lat = params[:lat]
    @lon = params[:lon]
    @area = params[:area]
    @address = params[:address]
    @url = params[:url]
  end
  
  def edit
    @review = Review.find(params[:id])
    @place = Place.find(@review.place_id)
  end
  
  def update
    place = Place.find(params[:id])
    review = Review.find(params.require(:place)[:reviews_attributes]["0"][:id].to_i)
    
    place.update(place_params_update)
    review.update(review_params_update)
  end
  
  def create
    review_place = params.require(:place)[:place_name]
    
    if Place.find_by(place_name: review_place)
      @place_id = Place.find_by(place_name: review_place)[:id]
      Review.create(review_params)
    else
      Place.create(place_params)
    end
  end
  
  private
  def place_params
      params.require(:place).permit(:place_name, :address, :area_name, :lat, :lon, :url, reviews_attributes: [:category, :recommend_rate, :wifi_rate, :text, :user_id, :socket, :image])
  end
  
  def review_params
    params.require(:place)[:reviews_attributes]["0"].permit(:category, :recommend_rate, :wifi_rate, :text,:user_id,:socket, :image).merge(place_id: @place_id)
  end
  
  def place_params_update
    params.require(:place).permit(:area_name)
  end
  def review_params_update
  params.require(:place)[:reviews_attributes]["0"].permit(:category, :recommend_rate, :wifi_rate, :text, :user_id, :socket,:image)
  end
end
 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_action  :authenticate_user!, only: [:destroy]
  
  def index
    places = Place.where(area_name: params[:format]).includes(:reviews)
    @places = places.reject{|place| place.reviews.blank? }
    
  end
  
  def search
    keyword = "%#{params[:keyword]}%"
    @places = Place.where('address LIKE(?)', keyword)
  end
  
  def destroy
    review = Review.find(params[:id])
    review.delete
    redirect_back(fallback_location: user_path)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for twitter
  def twitter
    callback_for(:twitter)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @reviews = Review.where(user_id: params[:id]).includes(:place).order("updated_at DESC").page(params[:page]).per(3)
    @user = User.find(params[:id])
    @total_reviews_num = @user.reviews.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudySpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <%= include_gon %>
  </head>

  <body>
    <header>
      <div class="menu-logo">Study Space</div>
      <div class="toggle"><i class="fas fa-bars fa-2x"></i></div>
        <nav>
          <div class="home">Home</div>
              <% if user_signed_in? %>
                <%= link_to 'マイページ', user_path(current_user.id), class:"bar-btn btn",data: {"turbolinks" => false} %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"bar-btn btn",data: {"turbolinks" => false} %>
              <% else %>
                <%= link_to 'ログイン', new_user_session_path, class:"bar-btn btn",data: {"turbolinks" => false} %>
                <%= link_to 'ユーザー登録', new_user_registration_path, class:"bar-btn btn",data: {"turbolinks" => false} %>
              <% end %>
          <div class="twitter">
            <a id="tweet-icon-link" href="http://twitter.com/share?url=[シェアするURL]&text=Study Space~勉強スペースレビューアプリ~&hashtags=studyspace" target="_blank"><i class="twitter-icon fab fa-twitter fa-2x"></i></a>
          </div>
        </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/places/create.html.erb
<div class="create-wrap">
  <h3>レビューが投稿されました！</h3>
  <p>ご協力ありがとうございます</p>
  
  <%= link_to 'ホームに戻る', root_path ,data: {"turbolinks" => false} %>
</div>

app/views/places/edit.html.erb
<div class="background">
  <div class="new-form">
    <div class="new-form-content">
      <%= form_for (@place) do |f| %>
      <p class="review-place_name"><i class="fas fa-map-marker-alt"></i> レビュー対象：<%= @place.place_name %></p>
        <%= f.fields_for :reviews do |r| %>
          <span>最寄駅：<%= f.text_field :area_name %></span><br>
          <span><i class="far fa-list-alt"></i> カテゴリ：<%= r.select :category, ["カフェ", "シェアオフィス","図書館","その他"] %></span><br>
          <span><i class="far fa-thumbs-up"></i> おすすめ度 (※1.絶対すすめない〜10.とてもすすめたい)</span>
          <%= r.select :recommend_rate, options_for_select((1..10).to_a) %><br>
          <span><i class="fas fa-plug"></i> コンセント有無</span>
          <%= r.select :socket, ["あり", "なし", "わからない"] %><br>
          <span><i class="fas fa-wifi"></i> Wifi速度(※1.とても遅い〜10.とても速い)</span>
          <%= r.select :wifi_rate, options_for_select((1..10).to_a) %><br>
          <span><i class="fas fa-pen"></i> 感想・コメント</span><br>
          <%= r.text_area :text, placeholder: "レビューを入力", autofocus: false, cols:"45", rows:"15", class:"comment-form" %><br>
          <%= r.file_field :image, placeholder: "画像アップロード", type: "file", style: "padding: 10px;" %>
          <%= r.hidden_field :user_id, value: current_user.id %>
        <% end %>
      </div>
      <%= f.submit "投稿する", class: "btn submit-btn" %>
      <% end %>
  </div>
</div>

app/views/places/index.html.erb
<div id="index-container">
  
  <div id="introduction">
    <p class="title">Welcome to<span class="menu-logo2">Study Space</span></p>
    <p class="introduction-phrase">カフェ、シェアオフィス、図書館、、、あなたはいつもどこで勉強していますか？<br>
    勉強する場所を探すのに手間取り、気がついたら時間がなくなっていた!<br>
    なんてことありませんか？<br></p>
    <p class="introduction-phrase">
    勉強する場所に困ったら、このサイトでみんなのおすすめスペースを探してみましょう。<br>
    また、お気に入りの場所をみんなとシェアしましょう。</p>
  </div>
  
  <div class="btn-left btn">
    <span type="button" class="button"><i class="fas fa-search-location"> </i> 勉強スペースを探す</span>
  </div>
  <div class="btn-right btn">
    <span type="button" class="button"><i class="far fa-edit"></i> レビューを書く</span>
  </div>
  
  <!--全体のレビュー場所のマップ-->
    <div id="main-map-container">
      <div id="main-map"></div>
    
      <script type="text/javascript" charset="utf-8" src="https://map.yahooapis.jp/js/V1/jsapi?appid=<%= @appid %>"></script>
      <script type="text/javascript">
         window.onload = function() {
          var ymap = new Y.Map("main-map");
          ymap.setConfigure("dragging", true);
          ymap.setConfigure("singleClickPan", true);
          ymap.setConfigure("doubleClickZoom", true);
          var control = new Y.ZoomControl();
          ymap.addControl(control);
          ymap.drawMap(new Y.LatLng(<%= @locations[0][:lon] %>,<%= @locations[0][:lat] %>), 12, Y.LayerSetId.NORMAL);
          
          var icon = new Y.Icon('/assets/icon.png');
          
          var data = gon.locations;
          var locationMarker = new Array();
          
          for ( var i = 0;  i < data.length ;  i++  ) {
            locationMarker.push({lon: data[i].lon, lat: data[i].lat, id: data[i].id, placeName: data[i].placeName});
            }
          for ( var i = 0;  i < locationMarker.length ;  i++ ){
            var marker = new Y.Marker(new Y.LatLng(locationMarker[i].lon,locationMarker[i].lat ), {icon: icon});
            var placeId = locationMarker[i].id;
            marker.bindInfoWindow(`<div data-turbolinks="false"><a href=/places/${placeId}>${locationMarker[i].placeName}</a></div>`);
            console.log(placeId);
            console.log(locationMarker[i].placeName);
            ymap.addFeature(marker);
            }
            ymap.addFeature(marker);
            }
      </script>
  </div>
  <!--ここからモーダル-->
  <div id="search-form">
    <div class="modal">
      <i class="far fa-times-circle close-btn fa-2x"></i>
      <div class="form-content">
        <span>レビュー対象場所を入力ください</span>
        <p>例：エクセルシオール　渋谷</p>
        <%= form_tag search_places_path, method: :get do %>
          <input name="keyword" placeholder="キーワードで検索" type="text" value="" class="form">
          <button class="btn-search btn" title="検索" type="submit"><i class="fab fa-sistrix fa-2x"></i></button></input>
        <% end %>
      </div>
    </div>
  </div>
  <div id="area-index">
    <div class="area-modal">
      <i class="far fa-times-circle close-btn fa-2x"></i>
      <div class="area-content">
        <span>最寄駅で探す（<%= @areas.length %>）</span>
        <div class="area-wrap">
          <% @areas.each do |area| %>
            <%= link_to area, reviews_path(area), class:"area" %>
          <% end %>
        </div>
      </div>
      <div class="address-search">
        <span>住所・エリアで検索</span>
        <%= form_tag search_reviews_path, method: :get do %>
        <input name="keyword" placeholder="例：渋谷" autocomplete="false" type="text" value="" class="search-form">
        <button class="btn-search btn" title="検索" type="submit"><i class="fab fa-sistrix fa-2x"></i></button></input>
        <% end %>
      </div>
    </div>
  </div>
      <!--ここまでモーダル-->

</div>

app/views/places/new.html.erb
<div class="background">
  <div class="new-form">
    <div class="new-form-content">
      <%= form_for @place do |f| %>
      <p class="review-place_name"><i class="fas fa-map-marker-alt"></i> レビュー対象：<%= @name %></p>
        <%= f.fields_for :reviews do |r| %>
          <span><i class="far fa-list-alt"></i> カテゴリ：<%= r.select :category, ["カフェ", "シェアオフィス","図書館","その他"] %></span><br>
          <span><i class="far fa-thumbs-up"></i> おすすめ度 (※1.絶対すすめない〜10.とてもすすめたい)</span>
          <%= r.select :recommend_rate, options_for_select((1..10).to_a) %><br>
          <span><i class="fas fa-plug"></i> コンセント有無</span>
          <%= r.select :socket, ["あり", "なし", "わからない"] %><br>
          <span><i class="fas fa-wifi"></i> Wifi速度(※1.とても遅い〜10.とても速い)</span>
          <%= r.select :wifi_rate, options_for_select((1..10).to_a) %><br>
          <span><i class="fas fa-pen"></i> 感想・コメント</span><br>
          <%= r.text_area :text, placeholder: "レビューを入力", autofocus: false, cols:"45", rows:"15", class:"comment-form" %><br>
          <%= r.file_field :image, placeholder: "画像アップロード", type: "file", style: "padding: 10px;" %>
          <%= r.hidden_field :user_id, value: current_user.id %>
        <% end %>
      </div>
      <%= f.hidden_field :place_name, value: @name.to_s %>
      <%= f.hidden_field :lat, value: @lat.to_f %>
      <%= f.hidden_field :lon, value: @lon.to_f %>
      <%= f.hidden_field :area_name, value: @area.to_s %>
      <%= f.hidden_field :address, value: @address %>
      <%= f.hidden_field :url, value: @url %>
      <%= f.submit "投稿する", class: "btn submit-btn" %>
      <% end %>
  </div>
</div>

app/views/places/search.html.erb
<div class="background">
  
  <span class="mb10">検索結果は<%= @places.count %>件です</span><br>
  <div class="keyword-result-content">
    <% @places.each do |place| %>
    <span><%= link_to "#{place[:name]}", new_place_path(place), class:"keyword-result",data: {"turbolinks" => false} %></span>
    <span>（<%= place[:address] %>）</span><br>
    <% end %>
  </div>
</div>

app/views/places/update.html.erb
<div class="create-wrap">
  <h3>レビューが更新されました！</h3>
  <p>ご協力ありがとうございます</p>
  
  <%= link_to 'ホームに戻る', root_path ,data: {"turbolinks" => false} %>
</div>

app/views/reviews/_reviews.html.erb
  <span>カテゴリー：<%= reviews.category %></span>
  <div class="wrap">
    おすすめ度：
    <% if reviews.recommend_rate <= 1 %>
      <span class="rate rate0"></span>
    <% elsif reviews.recommend_rate <= 2 %>
      <span class="rate rate1"></span>
    <% elsif reviews.recommend_rate <= 3 %>
      <span class="rate rate1-5"></span>
    <% elsif reviews.recommend_rate <= 4 %>
      <span class="rate rate2"></span>
    <% elsif reviews.recommend_rate <= 5 %>
      <span class="rate rate2-5"></span>
    <% elsif reviews.recommend_rate <= 6 %>
      <span class="rate rate3"></span>
    <% elsif reviews.recommend_rate <= 7 %>
      <span class="rate rate3-5"></span>
    <% elsif reviews.recommend_rate <= 8 %>
      <span class="rate rate4"></span>
    <% elsif reviews.recommend_rate <= 9 %>
      <span class="rate rate4-5"></span>
    <% elsif reviews.recommend_rate <= 10 %>
      <span class="rate rate5"></span>
    <% end %>
  </div>
  <div class="wrap">
    wifi速度：
    <% if reviews.wifi_rate <= 1 %>
      <span class="rate rate0"></span>
    <% elsif reviews.wifi_rate <= 2 %>
      <span class="rate rate1"></span>
    <% elsif reviews.wifi_rate <= 3 %>
      <span class="rate rate1-5"></span>
    <% elsif reviews.wifi_rate <= 4 %>
      <span class="rate rate2"></span>
    <% elsif reviews.wifi_rate <= 5 %>
      <span class="rate rate2-5"></span>
    <% elsif reviews.wifi_rate <= 6 %>
      <span class="rate rate3"></span>
    <% elsif reviews.wifi_rate <= 7 %>
      <span class="rate rate3-5"></span>
    <% elsif reviews.wifi_rate <= 8 %>
      <span class="rate rate4"></span>
    <% elsif reviews.wifi_rate <= 9 %>
      <span class="rate rate4-5"></span>
    <% elsif reviews.wifi_rate <= 10 %>
      <span class="rate rate5"></span>
    <% end %>
    
  </div>
  <p>レビュー：<%= reviews.text %></p>
  <p>更新日：<%= reviews.updated_at.to_date%></p>

app/views/reviews/index.html.erb
<div class="background">
  <div class="center-wrap">
    <h3 class="mb10"><%= @places[0][:area_name] %>駅周辺のレビュー：<%= @places.count %>件</h3>
      <% @places.each do |place| %>
      <div data-turbolinks="false" class="place-index">
        <span class="place-index-name"><%= link_to place[:place_name], place_path(place), class: "place-index-name" %></span>
      
        <div class="wrap">
          <span class="place-index-name"><i class="far fa-thumbs-up"></i>：</span>
          <% if place.review_average <= 1 %>
            <span class="rate rate0"></span>
          <% elsif place.review_average <= 2 %>
            <span class="rate rate1"></span>
          <% elsif place.review_average <= 3 %>
            <span class="rate rate1-5"></span>
          <% elsif place.review_average <= 4 %>
            <span class="rate rate2"></span>
          <% elsif place.review_average <= 5 %>
            <span class="rate rate2-5"></span>
          <% elsif place.review_average <= 6 %>
            <span class="rate rate3"></span>
          <% elsif place.review_average <= 7 %>
            <span class="rate rate3-5"></span>
          <% elsif place.review_average <= 8 %>
            <span class="rate rate4"></span>
          <% elsif place.review_average <= 9 %>
            <span class="rate rate4-5"></span>
          <% elsif place.review_average <= 10 %>
            <span class="rate rate5"></span>
          <% end %>
        </div>
        <div class="wrap">
          <span class="place-index-name"><i class="fas fa-wifi"></i>：</span>
          <% if place.wifi_average <= 1 %>
            <span class="rate rate0"></span>
          <% elsif place.wifi_average <= 2 %>
            <span class="rate rate1"></span>
          <% elsif place.wifi_average <= 3 %>
            <span class="rate rate1-5"></span>
          <% elsif place.wifi_average <= 4 %>
            <span class="rate rate2"></span>
          <% elsif place.wifi_average <= 5 %>
            <span class="rate rate2-5"></span>
          <% elsif place.wifi_average <= 6 %>
            <span class="rate rate3"></span>
          <% elsif place.wifi_average <= 7 %>
            <span class="rate rate3-5"></span>
          <% elsif place.wifi_average <= 8 %>
            <span class="rate rate4"></span>
          <% elsif place.wifi_average <= 9 %>
            <span class="rate rate4-5"></span>
          <% elsif place.wifi_average <= 10 %>
            <span class="rate rate5"></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/search.html.erb
<div class="background">
  <span class="search-result">検索結果：<%= @places.length %>件</span>
  <div class="result-content">
    <% @places.each do |place| %>
      <%= link_to place[:place_name], place_path(place[:id]),data: {"turbolinks" => false}, class: "result" %>
      （<%= place[:address] %>）<br>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
  <% if user_signed_in? && current_user.image.attached? %>
    <div class="user-info">
      <div class="user-edit">
        <span><%= image_tag @user.image, class:"user-icon" %><%= @user.user_name %> さんのページ</span>
        <%= link_to edit_user_registration_path, data: {"turbolinks" => false}, class:"user-link" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="user-info">
      <div class="user-edit">
        <span><%= @user.user_name %> さんのページ</span>
        <%= link_to edit_user_registration_path, data: {"turbolinks" => false}, class:"user-link" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    </div>
  <% end %>

<div class="mypage-background">
  <div class="pagenation-wrap">
    <span class="myreview-count">You have <%= @total_reviews_num %> reviews</span>
    <div class="page-wrap"><%= paginate @reviews %></div>
  </div>
  <% if @reviews.blank? %>
    <p>レビューは書かれていません</p>
  <% else %>
  <% @reviews.each do |review| %>
    <div class="myreview-wrap">
      <div class="myreview">
        <%= link_to review.place.place_name, review.place.url, class: "place-link" %>
        
        <div class="myreview-place">
          <span>最寄駅</span>：<%= review.place.area_name %>
          <span>カテゴリ</span>：<%= review.category %></span>
          <span><i class="far fa-thumbs-up"></i></span>
            <div>：
              <% if review.recommend_rate <= 1 %>
                <span class="rate rate0"></span>
              <% elsif review.recommend_rate <= 2 %>
                <span class="rate rate1"></span>
              <% elsif review.recommend_rate <= 3 %>
                <span class="rate rate1-5"></span>
              <% elsif review.recommend_rate <= 4 %>
                <span class="rate rate2"></span>
              <% elsif review.recommend_rate <= 5 %>
                <span class="rate rate2-5"></span>
              <% elsif review.recommend_rate <= 6 %>
                <span class="rate rate3"></span>
              <% elsif review.recommend_rate <= 7 %>
                <span class="rate rate3-5"></span>
              <% elsif review.recommend_rate <= 8 %>
                <span class="rate rate4"></span>
              <% elsif review.recommend_rate <= 9 %>
                <span class="rate rate4-5"></span>
              <% elsif review.recommend_rate <= 10 %>
                <span class="rate rate5"></span>
              <% end %>
            </div>
          <span><i class="fas fa-plug"></i></span><div>：<%= review.socket %></div>
          <span><i class="fas fa-wifi"></i></span>
          <div>：
            <% if review.wifi_rate <= 1 %>
              <span class="rate rate0"></span>
            <% elsif review.wifi_rate <= 2 %>
              <span class="rate rate1"></span>
            <% elsif review.wifi_rate <= 3 %>
              <span class="rate rate1-5"></span>
            <% elsif review.wifi_rate <= 4 %>
              <span class="rate rate2"></span>
            <% elsif review.wifi_rate <= 5 %>
              <span class="rate rate2-5"></span>
            <% elsif review.wifi_rate <= 6 %>
              <span class="rate rate3"></span>
            <% elsif review.wifi_rate <= 7 %>
              <span class="rate rate3-5"></span>
            <% elsif review.wifi_rate <= 8 %>
              <span class="rate rate4"></span>
            <% elsif review.wifi_rate <= 9 %>
              <span class="rate rate4-5"></span>
            <% elsif review.wifi_rate <= 10 %>
              <span class="rate rate5"></span>
            <% end %>
          </div>
          <span><i class="far fa-comment-dots"></i></span>：<%= review.text %>
          <span>更新日</span>：<%= review.updated_at.to_date %>
        </div>
        <% if review.image.attached? %>
          <div class="myimage" style="background-image: url(<%= rails_blob_path(review.image) %>)"></div>
        <% else %>
          <div class="noimage"><div class="noimage-message">No image</div></div>
        <% end %>
        
        <% if user_signed_in? && @user.id == current_user.id %>
          <div class="myreview-edit">
            <span><%= link_to edit_place_path(review),class: "myreview-edit-link", data: {"turbolinks" => false} do %>
              <i class="far fa-edit"></i>Edit</span>
            <% end %>
            <span><%= link_to review_path(review),class: "myreview-edit-link",method: :delete, data: {"turbolinks" => false} do %>
              <i class="far fa-edit"></i>Delete</span>
            <% end %>
          </div>
        <% end %>
        
      </div>
    </div>
  <% end %>
  <% end %>
</div>